language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls      # only required to get a coverage report on coveralls.io
# command to run tests
matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
      os: linux
    - python: 3.6
      env: TOXENV=py36
      os: linux
    - python: 3.7
      env: TOXENV=py37
      os: linux
    - python: 3.8
      env: TOXENV=py38
      os: linux
    - python: 3.9
      env: TOXENV=py39
      os: linux
    
      after_success:
        - pwd
        - coveralls --data_file libconfig/tests/.coverage
        - python-codacy-coverage -r /tmp/cov-single.xml
        - bash <(curl -s https://codecov.io/bash) -Z -c -f /tmp/cov-single.xml
    - python: 3.7-dev
      env: TOXENV=py37
      os: linux
    - language: generic
      env: TOXENV=py27
      os: osx
    - language: generic
      env: TOXENV=py36
      os: osx

before_install:
- bash ./ci/travis_before_install.sh
install:
  - bash ./ci/travis_install.sh

script:
  - tox
