# This workflow will install dependencies, create coverage tests and run Pytest Coverage Commentator
# For more information see: https://github.com/coroo/pytest-coverage-commentator
name: codecov

#on:
#  pull_request:
#    branches: 
#      - '*'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.7'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Generate coverage report
      run: |
        pip install pytest
        pip install coverage
        pip install coverage-badge
        pip install genbadge[all]
        coverage run -m pytest 
        coverage report -m 
        coverage xml
        coverage html
        genbadge coverage
    - name: archive code coverage html report
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: htmlcov
      #  coverage report -m > coverage.txt
      #  coverage-badge -o coverage.svg
      #  genbadge coverage

      #  lastln=$(tail -n1 coverage.txt)
      #  echo ${lastln}
      #  echo ${lastln:(-4)}
      # coverage run -m pytest > coverage.txt


        
